# Default flags for most of the files, some my differ as aggresive optimizatiaons are used
flags = ["-O3", "-m64", "-mavx", "-Wall", "-Wpedantic"]
debug_flags = ["-Og", "-g", "-mavx", "-m64", "-Wall",  "-Wpedantic"]
quick_flags = ["-Osize", "-m64", "-Wpedantic"]

Import('ARCH')
Import('BUILD_TYPE')
Import('TUNE')
Import('VULKAN')
Import('OPENGL')
Import('CC')

env = Environment()

# TODO: Environment initalization

if VULKAN == 'TRUE':
    Object('vkLoad.cpp')
if OPENGL == 'TRUE':
    Object('initGL.cpp')
    # TODO: Add target GL.dll/liblegacyrender.so