# Default flags for most of the files, some my differ as aggresive optimizatiaons are used
gcc_flags = ["-O3", "-m64", "-mavx", "-Wall", "-Wpedantic"]
gcc_debug_flags = ["-Og", "-g", "-mavx", "-m64", "-Wall",  "-Wpedantic"]
gcc_quick_flags = ["-Osize", "-m64", "-Wpedantic"]
msvc_flags = ["/O3", "/arch:AVX", "/Wall"]
msvc_debug_flags = ["/O1", "/Z7", "/arch:AVX", "/Wall"]
msvc_quick_flags = ["/Os", "/W4"]

Import('ARCH')
Import('BUILD_TYPE')
Import('TUNE')
Import('CC')

env = Environment()

# TODO: Environment initalization

Object('main.cpp')
Object('mem.cpp')
Object('gameplayMain.cpp')