# Default flags for most of the files, some my differ as aggresive optimizatiaons are used
flags = ["-O3", "-m64", "-mavx", "-flto"]
debug_flags = ["-Og", "-g", "-mavx", "-m64", "-Wall",  "-Wpedantic"]
quick_flags = ["-O", "-m64",]

Import('ARCH')
Import('BUILD_TYPE')
Import('TUNE')

env = Environment()

flags.append("-march=" + ARCH)
debug_flags.append("-march=" + ARCH)
quick_flags.append("-march=" + ARCH)

flags.append("-mtune=" + TUNE)
debug_flags.append("-mtune=" + TUNE)
quick_flags.append("-mtune=" + TUNE)

if BUILD_TYPE == "FINAL":
    env.Append( CPPFLAGS = flags )
    env["CPPDEFINES"] = { "_PRODUCTION_" : None }
elif BUILD_TYPE == "DEBUG":
    env.Append( CPPFLAGS = debug_flags )
    env["CPPDEFINES"] = { "_DEBUG_" : None }
elif BUILD_TYPE == "QUICK":
    env.Append( CPPFLAGS = quick_flags )
    env["CPPDEFINES"] = { "_QUICK_" : None }

Object('main.cpp')
Object('mem.cpp')
Object('gameplayMain.cpp')
Object('ldScene.cpp')
Object('time.cpp')