# TODO: Option to disable AVX
# TODO: Option to enable AVX2

flags = ["-O2", "-m64", "-mavx", "-msse4.2", "-flto", "-idirafter ../../include/sys"]
debug_flags = ["-Og", "-g", "-mavx",  "-msse4.2", "-m64", "-Wall",  "-Wpedantic", "-idirafter ../../include/sys"]
quick_flags = ["-O", "-m64", "-msse4.2", "-idirafter ../../include/sys"] # TODO: Option for enabling quick build with AVX and AVX2

Import('ARCH')
Import('BUILD_TYPE')
Import('TUNE')

env = Environment( CPPPATH = "../../include/sys/soloud", CPPDEFINES = { "SOLOUD_SSE_INTRINSICS" : None } )

if BUILD_TYPE == "FINAL":
    env.Append( CPPFLAGS = flags, CPPDEFINES = { "_PRODUCTION_" : None } ) # SoLoud does not need the _MAVX_ define
elif BUILD_TYPE == "DEBUG":
    env.Append( CPPFLAGS = debug_flags, CPPDEFINES = { "_DEBUG_" : None } )
elif BUILD_TYPE == "QUICK":
    env.Append( CPPFLAGS = quick_flags, CPPDEFINES = { "_QUICK_" : None } )

flags.append("-march=" + ARCH)
debug_flags.append("-march=" + ARCH)
quick_flags.append("-march=" + ARCH)

flags.append("-mtune=" + TUNE)
debug_flags.append("-mtune=" + TUNE)
quick_flags.append("-mtune=" + TUNE)

files = ['backend/soloud_miniaudio.cpp'] # TODO: Load the relative path of each source file into this file

env.Library("libsoloud",)