# Default flags for most of the files, some my differ as aggresive optimizatiaons are used
flags = ["-O2", "-m64", "-mavx", "-flto", "-idirafter ../../include/sys"]
debug_flags = ["-Og", "-g", "-mavx", "-m64", "-Wall",  "-Wpedantic", "-idirafter ../../include/sys"]
quick_flags = ["-O", "-m64", "-idirafter ../../include/sys"]

Import('ARCH')
Import('BUILD_TYPE')
Import('TUNE')

env = Environment( CPPPATH = "../../include/sys/soloud", CPPDEFINES = { "SOLOUD_SSE_INTRINSICS" : None } )

if BUILD_TYPE == "FINAL":
    env.Append( CPPFLAGS = flags, CPPDEFINES = { "_PRODUCTION_" : None } )
elif BUILD_TYPE == "DEBUG":
    env.Append( CPPFLAGS = debug_flags, CPPDEFINES = { "_DEBUG_" : None } )
elif BUILD_TYPE == "QUICK":
    env.Append( CPPFLAGS = quick_flags, CPPDEFINES = { "_QUICK_" : None } )

flags.append("-march=" + ARCH)
debug_flags.append("-march=" + ARCH)
quick_flags.append("-march=" + ARCH)

flags.append("-mtune=" + TUNE)
debug_flags.append("-mtune=" + TUNE)
quick_flags.append("-mtune=" + TUNE)

files = ['backend/soloud_miniaudio.cpp'] # TODO: Load the relative path of each source file into this file

env.Library("libsoloud",)